### ISSUE TITLE
Card Duplicate Detection

### ISSUE THREAD

**Issue by brynmrk** [brynmrk/PokerInfo#59]
Add a button wherein if two or more player inputted a same card, this would alert all the players to reset their input and re-input their cards again.

_Refer to #58 for the placement/layout  in the screen._

**Comment by gxaAlfie** [comment]
This is related to [this](https://github.com/jnsoo123/poker_info_api/issues/72) API issue

**Comment by gxaAlfie** [comment]
PR: #71
